#!/usr/bin/env node

const fs = require('fs');
const dataDir = process.cwd(); // 'data';
const dataFile = 'crm.json';
const Table = require('cli-table');
const Fuse = require('fuse.js');
const moment = require('moment');

const defaultTableOptions = {
    chars: {'mid': '', 'left-mid': '', 'mid-mid': '', 'right-mid': ''}
};

const emailAlias = {
    'hoelt@fovea.cc': 'jc',
};

const fieldToText = (object, field) =>
    ['date', 'created', 'upgraded', 'churned', 'followup'].indexOf(field) >= 0
        ? (object[field] && moment(new Date(object[field])).fromNow() || '')
        : field === 'from'
        ? emailAlias[object[field]] || object[field].split(/[@.]/)[0]
        : (object[field] || '');

// const loadData = () =>
//     fs.readdirSync(dataDir).map((file) => require('./' + dataDir + '/' + file));

const loadData = () => {
    if (fs.existsSync(`${dataDir}/${dataFile}`))
        return require(`${dataDir}/${dataFile}`);
    else {
        console.error(`ERROR: File ${dataDir}/${dataFile} not found.`);
        console.error(`Run "crm init-crm" and I'll create it for you.`);
        process.exit(1);
    }
};
const saveData = (data) => {
    fs.copyFileSync(`${dataDir}/${dataFile}`, `${dataDir}/${dataFile}.bak`);
    fs.writeFileSync(`${dataDir}/${dataFile}`, JSON.stringify(data, null, 4));
};
const initData = () => {
    fs.writeFileSync(`${dataDir}/${dataFile}`, JSON.stringify([], null, 4));
};

// Reports
const companies = (data, filter, delColumns) => {
    const columns = ['name', 'url', 'address'];
    const displayColumns = columns.filter((c) => !delColumns || delColumns.indexOf(c) < 0);
    let out = data.map(x => x);
    if (filter) {
        const fuse = new Fuse(out, {
            keys: columns,
            matchAllTokens: true,
            threshold: 0.1,
            location: 0,
            distance: 100,
            findAllMatches: true,
        });
        out = fuse.search(filter);
    }
    out.printAsText = () => {
        const table = new Table(Object.assign(
            {head: displayColumns},
            defaultTableOptions));
        out.forEach((company) =>
            table.push(displayColumns.map(cname => fieldToText(company, cname))));
        console.log(table.toString());
    };
    return out;
};

const about = (data, filter, delColumns) => {
    let out = [];
    const columns = ['company', 'role', 'email'];
    const displayColumns = columns.filter((c) => !delColumns || delColumns.indexOf(c) < 0);
    data.forEach((company) => {
        company.contacts.forEach((c) => {
            const name = `${c.firstName} ${c.lastName}`.replace(/(^ )|( $)/g, '');
            out.push({
                company: company.name,
                role: c.role,
                email: `${name} <${c.email}>`,
            });
        });
    });
    if (filter) {
        const fuse = new Fuse(out, {
            keys: ['company', 'email'],
            matchAllTokens: true,
            threshold: 0.1,
            location: 0,
            distance: 500,
            findAllMatches: true,
        });
        out = fuse.search(filter);
    }

    out.printAsText = () => {

        const table = new Table( Object.assign(
            {head: displayColumns},
            defaultTableOptions));
        const companies = {};
        out.forEach((line) => {
            companies[line.company] = true;
            table.push(displayColumns.map(cname => fieldToText(line, cname)));
        });
        console.log('\nContacts:');
        console.log(table.toString());
        Object.keys(companies).forEach((company) => {
            console.log(`\nApps from ${company}:`);
            apps(data, company, ['company']).printAsText();
            console.log(`\nInteractions with ${company}:`);
            interactions(data, company, ['company']).printAsText();
        });
    };
    return out;
};


const contacts = (data, filter, delColumns) => {
    let out = [];
    const columns = ['company', 'role', 'email'];
    const displayColumns = columns.filter((c) => !delColumns || delColumns.indexOf(c) < 0);
    data.forEach((company) => {
        company.contacts.forEach((c) => {
            const name = `${c.firstName} ${c.lastName}`.replace(/(^ )|( $)/g, '');
            out.push({
                company: company.name,
                role: c.role,
                email: `${name} <${c.email}>`,
                rawEmail: c.email,
            });
        });
    });
    if (filter) {
        const fuse = new Fuse(out, {
            keys: ['company', 'email'],
            matchAllTokens: true,
            threshold: 0.1,
            location: 0,
            distance: 500,
            findAllMatches: true,
        });
        out = fuse.search(filter);
    }

    out.printAsText = () => {
        const table = new Table( Object.assign(
            {head: displayColumns},
            defaultTableOptions));
        out.forEach((line) =>
            table.push(displayColumns.map(cname => fieldToText(line, cname))));
        console.log(table.toString());
    };
    return out;
};

const apps = (data, filter, delColumns) => {
    let out = [];
    const columns = ['company', 'plan', 'created', 'upgraded', 'churned', 'name', 'email'];
    const displayColumns = columns.filter((c) => !delColumns || delColumns.indexOf(c) < 0);
    data.forEach((company) => {
        company.apps.forEach((app) => {
            out.push({
                company: company.name,
                created: app.createdAt,
                upgraded: app.upgradedAt,
                churned: app.churnedAt,
                email: app.email,
                name: app.appName,
                plan: app.plan,
            });
        });
    });
    if (filter) {
        const fuse = new Fuse(out, {
            keys: columns,
            matchAllTokens: true,
            threshold: 0.1,
            location: 0,
            distance: 100,
            findAllMatches: true,
        });
        out = fuse.search(filter);
    }
    out = out.sort((a, b) => (+new Date(a.date)) - (+new Date(b.date)));

    out.printAsText = () => {
        const table = new Table( Object.assign(
            {head: displayColumns},
            defaultTableOptions));
        out.forEach((line) =>
            table.push(displayColumns.map(cname => fieldToText(line, cname))));
        console.log(table.toString());
    };
    return out;
};

const interactions = (data, filter, delColumns) => {
    let out = [];
    const columns = ['company', 'kind', 'date', 'from', 'summary', 'followup'];
    const displayColumns = columns.filter((c) => !delColumns || delColumns.indexOf(c) < 0);
    data.forEach((company) => {
        company.apps.forEach((app) => {
            out.push({
                company: company.name,
                kind: 'system',
                date: app.createdAt || '',
                from: app.email,
                summary: `Registered ${app.appName}`,
                followup: '',
            });
            if (app.upgradedAt) {
                out.push({
                    company: company.name,
                    kind: 'system',
                    date: app.upgradedAt || '',
                    from: app.email,
                    summary: `Upgraded ${app.appName} to ${app.plan}`,
                    followup: '',
                });
            }
            if (app.churnedAt) {
                out.push({
                    company: company.name,
                    kind: 'system',
                    date: app.churnedAt || '',
                    from: app.email,
                    summary: `Churned ${app.appName}`,
                    followup: '',
                });
            }
        });
        company.interactions.forEach((interaction) => {
            out.push({
                company: company.name,
                kind: interaction.kind || '',
                date: interaction.date || '',
                from: interaction.from,
                summary: interaction.summary,
                followup: interaction.followUpDate || '',
            });
        });
    });
    if (filter) {
        const fuse = new Fuse(out, {
            keys: columns,
            matchAllTokens: true,
            threshold: 0.1,
            location: 0,
            distance: 100,
            findAllMatches: true,
        });
        out = fuse.search(filter);
    }
    out = out.sort((a, b) => (+new Date(a.date)) - (+new Date(b.date)));

    out.printAsText = () => {
        const table = new Table( Object.assign(
            {head: displayColumns},
            defaultTableOptions));
        out.forEach((line) =>
            table.push(displayColumns.map(cname => fieldToText(line, cname))));
        console.log(table.toString());
    };
    return out;
};

const readColumns = async (columns) => new Promise((resolve, reject) => {
    const typed = [];
    const object = {};
    const readline = require('readline');
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
        terminal: false
    });
    const onLine = function (cmd) {
        if (typed.length < columns.length) {
            object[columns[typed.length]] = cmd.replace(/([.?!]) /g, '$1\n');
            typed.push(cmd);
        }
        else if (cmd === 'y') {
            // console.log(JSON.stringify(object, null, 2));
            rl.off('line', onLine);
            return resolve(object);
        }
        else if (cmd === 'n') {
            rl.off('line', onLine);
            return reject();
        }

        if (typed.length < columns.length) {
            console.log(columns[typed.length] + ':');
        }
        else {
            console.log(JSON.stringify(object, null, 2));
            console.log('Confirm? (y/n)');
        }
    };
    console.log(columns[typed.length] + ':');
    rl.on('line', onLine);
});

const addApp = (data, filter) => {
    console.log('Please fill in app details:');
    readColumns(['appName', 'company', 'plan', 'email', 'createdAt', 'upgradedAt'])
    .catch(process.exit.bind(process, 1))
    .then((app) => {
        // If name is filled and there isn't a company with the given name.
        // Add it and save
        const companyName = app.company;
        const company = companies(data, companyName)[0]; // fuzzy search for the company
        delete app.company;
        if (company) {
            app.createdAt = (app.createdAt ? new Date(app.createdAt) : new Date()).toISOString();
            app.upgradedAt = app.upgradedAt ? new Date(app.upgradedAt).toISOString() : undefined;
            app.updatedAt = new Date().toISOString();
            // Find the company in the data
            const editCompany = data.find((c) => c.name === company.name);
            editCompany.apps.push(app);
            saveData(data);
            console.log('App added.');
            apps(data, company.name).printAsText();
            process.exit(0);
        }
        else {
            console.error(`ERROR: Company with name "${companyName}" doesn't exists.`);
            process.exit(1);
        }
    });
    return {printAsText: () => {}};
};

const addContact = (data, filter) => {
    console.log('Please fill in contact details:');
    readColumns(['firstName', 'lastName', 'role', 'company', 'email', 'url'])
    .catch(process.exit.bind(process, 1))
    .then((contact) => {
        // If name is filled and there isn't a company with the given name.
        // Add it and save
        const companyName = contact.company;
        const company = companies(data, companyName)[0]; // fuzzy search for the company
        delete contact.company;
        if (company) {
            contact.createdAt = new Date().toISOString();
            contact.updatedAt = new Date().toISOString();
            // Find the company in the data
            const editCompany = data.find((c) => c.name === company.name);
            editCompany.contacts.push(contact);
            saveData(data);
            console.log('Contact added.');
            contacts(data, company.name).printAsText();;
            process.exit(0);
        }
        else {
            console.error(`ERROR: Company with name "${companyName}" doesn't exists.`);
            process.exit(1);
        }
    });
    return {printAsText: () => {}};
};

const addInteraction = (data, filter) => {
    console.log('Please fill in interaction details:');
    readColumns(['company', 'kind', 'date', 'from', 'summary', 'followUpDate'])
    .catch(process.exit.bind(process, 1))
    .then((interaction) => {
        // Add it and save
        const companyName = interaction.company;
        const company = companies(data, companyName)[0]; // fuzzy search for the company
        delete interaction.company;
        const contact = contacts(data, interaction.from)[0];
        if (company && contact) {
            // interaction.createdAt = new Date().toISOString();
            // Find the company in the data
            interaction.date = interaction.date || new Date().toISOString();
            interaction.from = contact.rawEmail;
            const editCompany = data.find((c) => c.name === company.name);
            editCompany.interactions.push(interaction);
            saveData(data);
            console.log('Interaction added.');
            interactions(data, company.name).printAsText();;
            process.exit(0);
        }
        else {
            console.error(`ERROR: Company with name "${companyName}" doesn't exists.`);
            process.exit(1);
        }
    });
    return {printAsText: () => {}};
};

const addCompany = (data, filter) => {
    console.log('Please fill in company details:');
    readColumns(['name', 'address', 'url'])
    .catch(process.exit.bind(process, 1))
    .then((company) => {
        // If name is filled and there isn't a company with the given name.
        // Add it and save
        if (company.name && !data.find((c) => c.name.toLowerCase() === company.name.toLowerCase())) {
            company.createdAt = new Date().toISOString();
            company.updatedAt = new Date().toISOString();
            company.contacts = [];
            company.interactions = [];
            company.apps = [];
            data.push(company);
            saveData(data);
            console.log('Company added.');
            companies(data, company.name).printAsText();;
            process.exit(0);
        }
        else {
            console.error(`ERROR: A company with name "${company.name}" already exists.`);
            process.exit(1);
        }
    });
    return {printAsText: () => {}};
};

// Usage

const help = () => {
    console.log(
`usage: crm COMMAND [filter]

Available commands:

 - reports:

    i,interactions ... list of interactions.
    com,companies .... list of companies.
    con,contacts ..... list of contacts.
    a,apps ........... list of apps.
    about ............ all we know about a contact / company.

 - data entry:

    add-company ............ register a new company.
    add-contact ............ register a new contact.
    add-app ................ register a new app.
    add-i,add-interaction .. register a new customer interaction.

 - system:

    init-crm ........ create data file in current directory.

`);
};

const commands = {
    i:interactions,
    int:interactions,
    interactions,
    com:companies,
    company:companies,
    companies,
    con:contacts,
    contact:contacts,
    contacts,
    a:apps,
    app:apps,
    apps,
    about,
    'add-company': addCompany,
    'add-contact': addContact,
    'add-interaction': addInteraction,
    'add-i': addInteraction,
    'add-app': addApp,
};

if (process.argv[2] === 'init-crm') {
    initData();
    console.log('Done.');
    process.exit(0);
}

const data = loadData();
const command = commands[process.argv[2]];
if (!command) {
    help();
    process.exit(1);
}
const filter = process.argv.slice(3).join(' ');
const report = command(data, filter);
report.printAsText();
